language: bash

dist: bionic

env:
  - DOCKER_CLI_EXPERIMENTAL=enabled

env:
  global:
    - IMAGE_NAME=biarms/wordpress
    - VERSION=5.4.1-php7.4-fpm

sudo: required

services:
  - docker

# From https://docs.travis-ci.com/user/customizing-the-build/
# install: true

before_install:
  - BUILD_NUMBER=${TRAVIS_BUILD_NUMBER}
  - >
    if [[ "${TRAVIS_BRANCH}" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then
      echo "We are building the master branch: version is official version."
      BETA_MODE="false"
    else
      echo "We are not building the master branch (or we are in a PR mode). Building a beta version then"
      BETA_MODE="true"
    fi
  - echo "TRAVIS_BRANCH=${TRAVIS_BRANCH} - DOCKER_USERNAME=${DOCKER_USERNAME}"
  - docker version
  # From https://github.com/multiarch/qemu-user-static:
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

script:
  - make build-and-tests

after_success:
  - >
    if [[ "${BETA_MODE}" == "false" ]]; then
      echo "Building master branch. Let's also push the 'latest' tag on docker hub"
      docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
      make build-and-push
    fi
